### ISSUE TITLE
Error: Success

### ISSUE THREAD

**Issue by Anonymoosed** [shadowdare/Vanilla-App-Articles#23]
The addon could not be enabled because it generated a fatal error:
Success

Vanilla 2.1.8p2

**Comment by shadowdare** [comment]
I just enabled the Articles app on a fresh install of Vanilla 2.1.8p2 successfully and didn't get this error. Does enabling debug mode in the Vanilla config show more details about the fatal error?

**Comment by Anonymoosed** [comment]
Please close. Error not related to Vanilla-App-Articles.

**Comment by shadowdare** [comment]
Error was caused by a file permission issue. See: http://vanillaforums.org/discussion/comment/224054/#Comment_224054
