### ISSUE TITLE
Image resize

### ISSUE THREAD

**Issue by wolfgang1** [shadowdare/Vanilla-App-Articles#26]
Make the image resize automatic:
- the thumbnail
- the image inside the article when viewed in mobile theme.

It could be done via CSS I think.

**Comment by shadowdare** [comment]
Making the images resize automatically is called responsive images. I will look into adding some CSS to do this in a future release.

**Comment by shadowdare** [comment]
Closed by 5c9bc2247f3541f37e158b23b479b658233ee6b9.
