### ISSUE TITLE
Undefined variable/property errors in debug mode

### ISSUE THREAD

**Issue by 4311021x** [shadowdare/Vanilla-App-Articles#30]
There are various undefined variable and property errors in debug mode on the following pages:

new article page:
>Undefined variable: Author 
>applications/article/controllers/class.composecontroller.php line 233.
>library/core/class.dispatcher.php line 350.
>index.php line 46.
Undefined variable: Preview
applications/articles/controllers/class.composecontroller.php line 360.
library/core/class.dispatcher.php line 350.
index.php line 46.
Undefined property: ComposeController::$Category
applications/articles/views/compose/article.php line 25.
library/core/class.controller.php line 779.
library/core/class.controller.php line 1245

profile page:
>Undefined index: AuthorDisplayName
>applications/articles/settings/class.hooks.php line 544.
>library/core/class.pluginmanager.php line 705.
>library/core/class.pluginmanager.php line 638.
>library/core/class.pluggable.php line 144. 

edit profile page
>Undefined index: Articles.AuthorDisplayName
>applications/articles/settings/class.hooks.php line 509.
>library/core/class.pluginmanager.php line 705.
>library/core/class.pluginmanager.php line 638.
>library/core/class.pluggable.php line 144.
>Undefined index: Articles.AuthorBio
>applications/articles/settings/class.hooks.php line 510.
>library/core/class.pluginmanager.php line 705.
>library/core/class.pluginmanager.php line 638.
>library/core/class.pluggable.php line 144.

The errors on edit profile page seem to be disappearing when you've filled the AuthorDisplayName form.

**Comment by shadowdare** [comment]
Closed by 1792f4ef08ac95c62f770f2c690e20120ea37d23.
