### ISSUE TITLE
Fatal Error when posting new articles

### ISSUE THREAD

**Issue by 4311021x** [shadowdare/Vanilla-App-Articles#31]
The following error appears when posting new articles:

Fatal Error in ComposeController.Article();
Invalid argument supplied for foreach()
The error occurred on or near: applications/articles/controllers/class.composecontroller.php
~~~
338: } else {
339:     // If not editing.
340:     // Assign the new article's ID to any uploaded images.
341:     $UploadedImageIDs = $FormValues['UploadedImageIDs'];
342:     foreach($UploadedImageIDs as $ArticleMediaID) {
343:         $this->ArticleMediaModel->SetField($ArticleMediaID, 'ArticleID', $ArticleID);
344:     }
345: 
346:     $UploadedThumbnailID = (int)$FormValues['UploadedThumbnailID'];
~~~
Backtrace:

[applications/articles/controllers/class.composecontroller.php:342] PHP::Gdn_ErrorHandler();

[applications/articles/controllers/class.composecontroller.php:342] ComposeController->Article();

[library/core/class.dispatcher.php:350] PHP::call_user_func_array();

[index.php:46] Gdn_Dispatcher->Dispatch();

**Comment by shadowdare** [comment]
Closed by ff4cf4de08e4ae10cb1668915f51e1933be7c472.
